build: &build
  - build.gradle
  - app/core/build.gradle
  - app/common/build.gradle
  - app/proprietary/build.gradle

app: &app
  - app/core/src/main/java/**
  - app/common/src/main/java/**
  - app/proprietary/src/main/java/**

openapi: &openapi
  - build.gradle
  - app/core/build.gradle
  - app/core/src/main/java/**
  - app/common/build.gradle
  - app/common/src/main/java/**
  - app/proprietary/build.gradle
  - app/proprietary/src/main/java/**

project: &project
  - app/(common|core|proprietary)/src/(main|test)/java/**
  - app/(common|core|proprietary)/build.gradle
  - 'app/(common|core|proprietary)/src/(main|test)/resources/**/!(messages_*.properties|*.md)*'
  - exampleYmlFiles/**
  - gradle/**
  - libs/**
  - testing/**
  - build.gradle
  - Dockerfile
  - Dockerfile.fat
  - Dockerfile.ultra-lite
  - gradle.properties
  - gradlew
  - gradlew.bat
  - launch4jConfig.xml
  - settings.gradle