build: &build
  - build.gradle
  - app/core/build.gradle
  - app/common/build.gradle
  - app/proprietary/build.gradle

app: &app
  - app/core/src/main/java/**
  - 'app/core/src/main/resources/!(messages_)*'
  - app/common/src/main/java/**
  - app/proprietary/src/main/java/**
  - src/main/java/**
  - '!**/**/*.md'