build: &build
  - build.gradle
  - app/core/build.gradle
  - app/common/build.gradle
  - app/proprietary/build.gradle

app: &app
  - app/(common|core|proprietary)/src/main/java/**
  - app/(common|core|proprietary)/build.gradle
  - 'app/(common|core|proprietary)/src/main/resources/!(static)/**/!(messages_*.properties|*.md)*'
  - gradle/**
  - libs/**
  - testing/**
  - build.gradle
  - Dockerfile
  - Dockerfile.fat
  - Dockerfile.ultra-lite
  - gradle.properties
  - gradlew
  - gradlew.bat
  - launch4jConfig.xml
  - settings.gradle