build: &build
  - build.gradle
  - app/core/build.gradle
  - app/common/build.gradle
  - app/proprietary/build.gradle

app: &app
  - app/(common|core|proprietary)/src/main/java/**
  - app/(common|core|proprietary)/build.gradle
  - 'app/(common|core|proprietary)/src/main/resources/**/!(messages_*.properties)*'
  # - app/common/src/main/java/**
  # - app/proprietary/src/main/java/**
  # - src/main/java/**
  # - '!**/**/*.md'