name: 'Common Setup'
description: 'Checkout repository and apply runner hardening'

inputs:
  egress-policy:
    description: 'Egress policy to apply (z. B. audit, deny)'
    required: true
    default: 'audit'
  fetch-depth:
    description: 'Depth of the git history to fetch'
    required: false
    default: '1'
  path:
    description: 'Path to checkout'
    required: false
    default: '${{ github.workspace }}'
  ref:
    description: 'Reference branch or tag to checkout'
    required: false
    default: 'main'
  repository:
    description: 'Repository to checkout (defaults to current repository)'
    required: false
    default: '${{ github.repository }}'
  token:
    description: 'GitHub token to use for checkout'
    required: false
    default: '${{ secrets.GITHUB_TOKEN }}'
  persist-credentials:
    description: 'Whether to persist credentials after checkout'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: ${{ inputs.egress-policy }}

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        persist-credentials: ${{ inputs.persist-credentials }}
