name: "Build & Docker Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted-ubuntu-24-10

    permissions:
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        jdk-version: [17, 21]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: "temurin"

      - name: PR | Generate verification metadata with signatures and checksums for dependabot[bot]
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          ./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata sha256 --refresh-dependencies help
          ./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata sha256,pgp --refresh-keys --export-keys --refresh-dependencies help

      - name: Build with Gradle (without spring security)
        id: build_without_security
        run: |
          ./gradlew clean build 2> >(tee gradle-error-${{ matrix.jdk-version }}-false.log >&2) || echo $? > gradle-exit-code-${{ matrix.jdk-version }}-false.txt
        env:
          DOCKER_ENABLE_SECURITY: false

      - name: Check Gradle Build Exit Code (without spring security)
        if: ${{ always() && steps.build_without_security.conclusion }}
        id: build_without_security_exit_code
        run: |
          if [ -f gradle-exit-code-${{ matrix.jdk-version }}-false.txt ]; then
            # error_output=$(cat gradle-error-${{ matrix.jdk-version }}-false.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")

            echo "error_output_false<<EOF" >> $GITHUB_ENV
            cat gradle-error-${{ matrix.jdk-version }}-false.log >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

            exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-false.txt)
            exit ${exit_code:-1}
          fi

      - name: Check Gradle Build failure (without spring security)
        if: ${{ always() && steps.build_without_security_exit_code.conclusion == 'failure' }}
        run: |
          if echo "${{ env.error_output_false }}" | grep -q 'dependency-verification-report.html'; then
            echo "write_comment_without_security=true" >> $GITHUB_ENV
          else
            echo "write_comment_without_security=false" >> $GITHUB_ENV
          fi

      - name: Build with Gradle (with spring security)
        id: build_with_security
        run: |
          ./gradlew clean build 2> >(tee gradle-error-${{ matrix.jdk-version }}-true.log >&2) || echo $? > gradle-exit-code-${{ matrix.jdk-version }}-true.txt
        env:
          DOCKER_ENABLE_SECURITY: true

      - name: Check Gradle Build Exit Code (with spring security)
        if: ${{ always() && steps.build_with_security.conclusion }}
        id: build_with_security_exit_code
        run: |
          if [ -f gradle-exit-code-${{ matrix.jdk-version }}-true.txt ]; then
            # error_output=$(cat gradle-error-${{ matrix.jdk-version }}-true.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")

            echo "error_output_true<<EOF" >> $GITHUB_ENV
            cat gradle-error-${{ matrix.jdk-version }}-true.log >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

            exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-true.txt)
            exit ${exit_code:-1}
          fi

      - name: Check Gradle Build failure (with spring security)
        if: ${{ always() && steps.build_with_security_exit_code.conclusion == 'failure' }}
        run: |
          if echo "${{ env.error_output_true }}" | grep -q 'dependency-verification-report.html'; then
            echo "write_comment_with_security=true" >> $GITHUB_ENV
          else
            echo "write_comment_with_security=false" >> $GITHUB_ENV
          fi

      - name: PR | Delete comment
        if: ${{ always() && github.event_name == 'pull_request' && steps.build_with_security_exit_code.conclusion == 'success' && steps.build_without_security_exit_code.conclusion == 'success' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { GITHUB_REPOSITORY } = process.env;
            const [repoOwner, repoName] = GITHUB_REPOSITORY.split('/');
            const prNumber = context.issue.number;

            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: repoOwner,
              repo: repoName,
              issue_number: prNumber
            });

            const comment = comments.data.find(c => c.body.includes(`🚨 **Gradle Build Failed** 🚨`));

            // Only allow the action user to update comments
            const expectedActor = "github-actions[bot]";

            if (comment && comment.user.login === expectedActor) {
              // deleted existing comment
              await github.rest.issues.deleteComment({
                owner: repoOwner,
                repo: repoName,
                comment_id: comment.id
              });
              console.log("Deleted existing comment.");
            }

      - name: PR | Post comment
        if: ${{ always() && github.event_name == 'pull_request' && ((steps.build_with_security_exit_code.conclusion == 'failure' && env.write_comment_with_security == 'true') || (steps.build_without_security_exit_code.conclusion == 'failure' && env.write_comment_without_security == 'true')) }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { GITHUB_REPOSITORY, error_output_true, error_output_false, combined_error_logs } = process.env;
            const [repoOwner, repoName] = GITHUB_REPOSITORY.split('/');
            const prNumber = context.issue.number;

            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: repoOwner,
              repo: repoName,
              issue_number: prNumber
            });

            const comment = comments.data.find(c => c.body.includes(`🚨 **Gradle Build Failed** 🚨`));

            // Only allow the action user to update comments
            const expectedActor = "github-actions[bot]";

            // Build the comment content
            let bodyComment = "🚨 **Gradle Build Failed** 🚨\n\n";
            bodyComment += "To resolve the dependency verification issue, execute the following commands step by step to update the dependency metadata and push the changes to this pull request:\n\n";
            bodyComment += "```bash\n";
            bodyComment += "./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata sha256 --refresh-dependencies help\n\n";
            bodyComment += "```\n\n";
            bodyComment += "```bash\n";
            bodyComment += "./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata sha256,pgp --refresh-keys --export-keys --refresh-dependencies help\n";
            bodyComment += "```\n\n";
            bodyComment += "For further details, refer to the [Dependency Management Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/DeveloperGuide.md#managing-dependencies).\n";


            if (!comment && (process.env.error_output_true || process.env.error_output_false)) {
              // Create new comment if no existing comment is found
              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: prNumber,
                body: bodyComment
              });
              console.log("Created new comment.");
            } else if (comment && comment.user.login === expectedActor) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: repoOwner,
                repo: repoName,
                comment_id: comment.id,
                body: bodyComment
              });
              console.log("Updated existing comment.");
            } else {
              console.log("Comment update attempt denied. Actor does not match.");
            }

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: test-reports-jdk-${{ matrix.jdk-version }}
          path: |
            gradle-error-${{ matrix.jdk-version }}-true.log
            gradle-error-${{ matrix.jdk-version }}-false.log
            build/reports/tests/
            build/test-results/
            build/reports/problems/
          retention-days: 3

  check-licence:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 21
          distribution: "temurin"

      - name: check the licenses for compatibility
        run: ./gradlew clean checkLicense

      - name: FAILED - check the licenses for compatibility
        if: failure()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: dependencies-without-allowed-license.json
          path: |
            build/reports/dependency-license/dependencies-without-allowed-license.json
          retention-days: 3

  docker-compose-tests:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main' ||
    #     (github.event_name == 'pull_request' &&
    #     contains(github.event.pull_request.labels.*.name, 'licenses') == false &&
    #     (
    #       contains(github.event.pull_request.labels.*.name, 'Front End') ||
    #       contains(github.event.pull_request.labels.*.name, 'Java') ||
    #       contains(github.event.pull_request.labels.*.name, 'Back End') ||
    #       contains(github.event.pull_request.labels.*.name, 'Security') ||
    #       contains(github.event.pull_request.labels.*.name, 'API') ||
    #       contains(github.event.pull_request.labels.*.name, 'Docker') ||
    #       contains(github.event.pull_request.labels.*.name, 'Test')
    #     )
    #     )

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Java 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Install Docker Compose
        run: |
          sudo curl -SL "https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Pip requirements
        run: |
          pip install --require-hashes -r ./testing/cucumber/requirements.txt

      - run: echo ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

      - name: Run Docker Compose Tests
        run: |
          # chmod +x ./testing/test_webpages.sh
          chmod +x ./testing/test.sh
          ./testing/test.sh "${{ github.event.pull_request.user.login == 'dependabot[bot]' }}"
