name: Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-py:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev \
          libxcursor-dev libxrandr-dev libxinerama-dev build-essential liblcms2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel  # Install necessary build tools

      - name: Clone MuPDF repository
        run: |
          git clone https://github.com/ArtifexSoftware/mupdf.git
          cd mupdf
          git submodule update --init --recursive

      - name: Build MuPDF
        run: |
          cd mupdf
          make clean
          make prefix=/usr/local install

      - name: Validate installation
        run: |
          mupdf-gl --version
          muraster --version
          mutool --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel  # Install necessary build tools

      - name: Clone MuPDF repository
        run: |
          git clone https://github.com/ArtifexSoftware/mupdf.git

      - name: List files in the MuPDF directory
        run: |
          cd mupdf
          ls -la

      - name: Check the setup.py script
        run: |
          cd mupdf
          head -n 20 setup.py

      - name: Build MuPDF package
        run: |
          cd mupdf
          python setup.py sdist bdist_wheel

      - name: Upload distribution
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: dist
          path: |
            dist/*.tar.gz
            dist/*.whl

      - name: Test the package
        run: |
          pip install dist/*.whl  # Install the built package

      - name: Set up git config
        run: |
          git config --global user.email "GitHub Action <action@github.com>"
          git config --global user.name "GitHub Action <action@github.com>"

      - name: Run git add
        run: |
          git add .
          git diff --staged --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Build MuPDF"
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: build-mupdf-js
          title: "Update Build MuPDF"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: licenses
          draft: false
          delete-branch: true
