name: A Secure Check Properties

on:
  workflow_dispatch:
    inputs:
      files:
        description: "List of changed files"
        required: true
      actor:
        description: "User who opened the PR"
        required: true
      ref_file:
        description: "Reference file to use"
        required: true
      pr_number:
        description: "Pull Request number"
        required: true
      branch_name:
        description: "Branch to check"
        required: true

permissions:
  contents: read

jobs:
  check-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
      - name: Determine reference file
        id: determine-ref-file
        run: |
          echo "Determining reference file..."
          if echo "${{ github.event.inputs.files }}" | grep -q "src/main/resources/messages_en_GB.properties"; then
            echo "Reference file found in PR branch."
            echo "REFERENCE_FILE=pr-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          else
            echo "Reference file will use main branch."
            echo "REFERENCE_FILE=main-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          fi
          echo "REFERENCE_FILE=$REFERENCE_FILE"

      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.inputs.branch_name }}
          path: pr-branch
          fetch-depth: 0

      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          path: main-branch
          fetch-depth: 0

      - name: Log inputs
        run: |
          echo "Changed files: ${{ github.event.inputs.files }}"
          echo "Actor: ${{ github.event.inputs.actor }}"
          echo "Reference file: ${{ github.event.inputs.ref_file }}"
          echo "Reference file from Branch: ${{ env.REFERENCE_FILE }}"
          echo "Pull Request number: ${{ github.event.inputs.pr_number }}"
          echo "Branch: ${{ github.event.inputs.branch_name }}"

      - name: Run Python script
        run: |
          echo "Running Python script to check files..."
          python main-branch/.github/scripts/check_language_properties.py \
            --actor ${{ github.event.inputs.actor }} \
            --reference-file "${{ env.REFERENCE_FILE }}" \
            --branch pr-branch \
            --files "${{ github.event.inputs.files }}" > result.txt || true

      - name: Capture output
        id: capture-output
        run: |
          if [ -f result.txt ] && [ -s result.txt ]; then
            echo "Test, capturing output..."
            SCRIPT_OUTPUT=$(cat result.txt)
            echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
            echo "$SCRIPT_OUTPUT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "${SCRIPT_OUTPUT}"

            # Set FAIL_JOB to true if SCRIPT_OUTPUT contains ❌
            if [[ "$SCRIPT_OUTPUT" == *"❌"* ]]; then
              echo "FAIL_JOB=true" >> $GITHUB_ENV
            else
              echo "FAIL_JOB=false" >> $GITHUB_ENV
            fi
          else
            echo "No update found."
            echo "SCRIPT_OUTPUT=" >> $GITHUB_ENV
            echo "FAIL_JOB=false" >> $GITHUB_ENV
          fi

      - name: Post comment on PR
        if: env.SCRIPT_OUTPUT != ''
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const SCRIPT_OUTPUT = process.env.SCRIPT_OUTPUT || "No output provided.";

            const prNumber = parseInt("${{ github.event.inputs.pr_number }}", 10);

            // Überprüfen, ob der Kontext korrekt ist
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: repoOwner,
              repo: repoName,
              issue_number: prNumber
            });

            const comment = comments.data.find(c => c.body.includes("## 🚀 Translation Verification Summary"));
            const expectedActor = "github-actions[bot]";

            if (comment && comment.user.login === expectedActor) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: repoOwner,
                repo: repoName,
                comment_id: comment.id,
                body: `## 🚀 Translation Verification Summary\n\n\n${SCRIPT_OUTPUT}\n`
              });
              console.log("Updated existing comment.");
            } else if (!comment) {
              // Create new comment if no existing comment is found
              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: prNumber,
                body: `## 🚀 Translation Verification Summary\n\n\n${SCRIPT_OUTPUT}\n`
              });
              console.log("Created new comment.");
            } else {
              console.log("Comment update attempt denied. Actor does not match.");
            }

      - name: Fail job if errors found
        run: |
          FAIL_JOB=$(cat $GITHUB_STATE | grep FAIL_JOB | cut -d '=' -f2)
          if [[ "$FAIL_JOB" == "true" ]]; then
            echo "Failing the job because errors were detected."
            exit 1
          fi
